### ISSUE TITLE
issue when building from source

### ISSUE THREAD

**Issue by ajajar** [blockcollider/bcnode#185]
Hey guys,

After installing all packages and successfully running the command `npm install`,  I run `npm run dist` I have this error 

`error: failed to run custom build command for bcnode-native v0.1.0 (file:///Users/ajajara/Desktop/BCMining/bcnode/native)
process didn't exit successfully: /Users/ajajara/Desktop/BCMining/bcnode/native/target/debug/build/bcnode-native-37f47c494df02aca/build-script-build (exit code: 101)
--- stderr
thread 'main' panicked at 'protoc version: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
note: Run with RUST_BACKTRACE=1 for a backtrace.`

`warning: build failed, waiting for other jobs to finish...
error: build failed`

Any one had this error ?

Thanks

**Comment by korczis** [comment]
@ajajar it seems you are missing [protobuf v3](https://developers.google.com/protocol-buffers/docs/proto3)

protobuf3 needs to be installed and available on PATH

**Comment by korczis** [comment]
Closing, explanation in previous comment.
