### ISSUE TITLE
ERROR	rover.btc.controller Uncaught exception

### ISSUE THREAD

**Issue by CryptoSmileee** [blockcollider/bcnode#235]
### Prerequisites

- [x] Are you running the latest version?
- [x] Did you build from source?
- [x] Do you use the master branch?
- [x] Did you check the README.md for steps to run?
- [x] Did you check logs? (either in console or in `_logs` directory)

For more information, see the `CONTRIBUTING` guide.

### Description
The btc controller had an uncaught exception when I start the miner.

### Steps to Reproduce

1. Run latest version of the miner

**Expected behavior:** 
The error should be handled in a correct way.

**Actual behavior:** 
Error when I started the miner. 

### Versions
(0.5.5/9905e51)

#### Application (required)

You can get this information:
- Built from source
- Run the miner using forever:
`forever start ./bin/cli start --miner-key CryptoSmileee --node --ui --ws`

#### Environment (optional but helpful)

- OS Version (Ubuntu 17.10)
- Nodejs (v9.11.1)
- Rust (rustc 1.27.0-nightly (ad610bed8 2018-04-11))

### Logs
Full Log: http://telobot.com/UP_o.log

    2018-05-08T17:11:39.014Z INFO	server.index Server available at http://0.0.0.0:3000 
    2018-05-08T17:11:40.248Z ERROR	rover.btc.controller Uncaught exception: { stack: 
    [ 'Error: Unsupported message command: encinit',
     'at Messages._buildFromBuffer (/home/bc/bcnode/node_modules/bitcore-p2p/lib/messages/index.js:101:11)',
     'at Messages.parseBuffer (/home/bc/bcnode/node_modules/bitcore-p2p/lib/messages/index.js:74:15)',
     'at Peer._readMessage (/home/bc/bcnode/node_modules/bitcore-p2p/lib/peer.js:219:31)',
     'at Socket.<anonymous> (/home/bc/bcnode/node_modules/bitcore-p2p/lib/peer.js:167:10)',
     'at Socket.emit (events.js:180:13)',
     'at addChunk (_stream_readable.js:274:12)',
     'at readableAddChunk (_stream_readable.js:261:11)',
     'at Socket.Readable.push (_stream_readable.js:218:10)',
     'at TCP.onread (net.js:581:20)' ],
      message: 'Unsupported message command: encinit' }

**Comment by akloboucnik** [comment]
Resolved by #250
